language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6.1
install:
  - pip install Django==$DJANGO_VERSION django-discover-runner
  - pip install djangorestframework django-tastypie coveralls
script: make test
after_success:
    coveralls
